<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MiPushDesk</RootNamespace>
    <AssemblyName>MiPushDesk</AssemblyName>
    <Version>1.4.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\MiPushDesk.ico</ApplicationIcon>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <EnableMsixTooling>false</EnableMsixTooling>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MiPushDesk.Core\MiPushDesk.Core.csproj" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <Content Include="Assets\*.png;Assets\*.ico;Assets\*.svg" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\AppIcons\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <Target Name="PublishXamlResources" AfterTargets="ComputeFilesToPublish">
    <ItemGroup>
      <XamlResource Include="$(TargetDir)**\*.xbf" />
      <ResolvedFileToPublish Include="$(TargetDir)$(AssemblyName).pri">
        <RelativePath>$(AssemblyName).pri</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
      <ResolvedFileToPublish Include="@(XamlResource)">
        <RelativePath>%(XamlResource.RecursiveDir)%(XamlResource.Filename)%(XamlResource.Extension)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>
